// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PageInfo struct {
	HasNexPage      bool   `json:"hasNexPage"`
	HasPreviousPage bool   `json:"hasPreviousPage"`
	StartCursor     string `json:"startCursor"`
	EndCurosor      string `json:"endCurosor"`
}

type People struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	Gender *string `json:"gender"`
	Height *string `json:"height"`
}

type PeopleConnection struct {
	Edges      []*PeopleEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type PeopleEdge struct {
	Cursor string  `json:"cursor"`
	Node   *People `json:"node"`
}
